media:
  input: content/media
  output: /media
content:
  - name: blog
    label: Blog
    type: collection
    path: 'content/blog'
    filename: "{fields.title}.md"
    view:
      fields: [ draft, title, description, date, tags]
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: date
        label: Date
        type: date        
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
        required: true    
      - name: tags
        label: Tags
        type: string
        list: true
        fields:
          - name: tag
            label: Tag
            type: string   
      - name: body
        label: Body
        type: rich-text            
  - name: home
    label: Homepage
    path: _data/home.js
    type: file
    fields:
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
  - name: metadata
    label: Site Settings
    path: _data/metadata.js
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: language
        label: Website language
        type: string     
      - name: author
        label: Website author
        type: object
        fields:
          - name: name
            label: Author name
            type: string
          - name: email
            label: Author email
            type: string            
          - name: url
            label: Author URL
            type: string
            pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$  
  - name: about
    label: About
    path: content/about/index.md
    type: file
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text         